#!/usr/bin/env python
"""Prepare a minimal Hugging Face model repository payload locally."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

MODEL_CARD = """---
library_name: scikit-learn
tags:
- time-series-forecasting
- finance
- gold
- silver
private: true
---

# Gold/Silver next-day return model

This repository contains the selected local research model for next-day log-return signals on Gold and Silver.

## Intended use

Research and educational use only. This is not investment advice and the model is not guaranteed to be profitable.

## Contents

- `gold_silver_bundle.joblib`: selected Gold and Silver estimators, feature order and configuration.
- `experiment_summary.json`: validation and locked test metrics generated by the local experiment.

The input data is downloaded at inference time from the configured public sources. Raw market data is intentionally not redistributed here.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bundle", default="models/gold_silver_bundle.joblib")
    parser.add_argument("--output", default="hf_export")
    args = parser.parse_args()
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    shutil.copy2(args.bundle, output / "gold_silver_bundle.joblib")
    summary = Path("reports/experiment_summary.json")
    if summary.exists():
        shutil.copy2(summary, output / summary.name)
    (output / "README.md").write_text(MODEL_CARD, encoding="utf-8")
    (output / "metadata.json").write_text(json.dumps({"source_bundle": str(args.bundle), "private_by_default": True}, indent=2), encoding="utf-8")
    print(f"Prepared {output}; upload with: hf upload <namespace>/<repo> {output} --private")


if __name__ == "__main__":
    main()
